### ISSUE TITLE
Crash in Unity 5.3.1f1

### ISSUE THREAD

**Issue by toto5100** [brendanwalker/psmove-unity5#10]
Hello,
I tried to use your api in Unity, and it works, but only one time. When i launch Unity, launch the demo scene and start playmode, it works, but when i stop and replay, it does not work (psmove not lighting up) and it crashes Unity.

**Comment by brendanwalker** [comment]
Yikes! That sounds like maybe the ps3eye camera is getting stuck open and then psmoveapi fails to open the camera a second time. I'll take a look at that tonight. By the way, what version of windows are you running? I usually test on win10 at home.

**Comment by toto5100** [comment]
I'm on Windows 8.1. I forgot to say that the second time, the demo scene works, but psmove is not initilizing, with this in the unity console : Setting Up PSMove tracking context. Also, the ps3camera red light is however on.

**Comment by brendanwalker** [comment]
So the "Setting Up PSMove tracking context" line means that the PSMoveManager thread is trying to open up the ps3eye camera. If it's crashing after that, that probably means that it failed to open the camera and the rest of the tracker setup isn't handling that error case and choking on it (something I need to fix). If the red light stays on after stopping the demo scene the first time that means the camera is getting stuck open. You can verify if this is the case by doing the following:

1. Close unity
1. Unplug the camera and plug it back in (blue light is on, red is off)
1. Run ps3eye_sdl in the Assets/Plugin folder to make sure the camera is working (red light should now be on)
1. Close ps3eye_sdl (red light is now off)
1. Open the unity project
1. Play the scene (red light is now on)
1. Stop the scene (red light should now be off)
1. Launch ps3eye_sdl again

If ps3eye_sdl fails to open again then the camera is in fact getting stuck open. You can get around this by unplugging and re-plugging in the camera, but this is obviously a pain in the long run. I'll see if I can reproduce this issue tonight in win10.

**Comment by toto5100** [comment]
I tried what you said and the ps3eye_sdl shows image. When i play the first time it works. The second time, it does not always crash (i tried multiple times), but move does not work. Then the third time, Unity freezes and i have to force quit. I will download the new Unity version the see if it changes something.

**Comment by brendanwalker** [comment]
I was able to repro this on my win10 machine at home. Looking into the issue now.

**Comment by brendanwalker** [comment]
I figured out the issue. There was a very subtle bug in the new PS3EyeDriver code that only manifests when you stop and restart the camera in the same process (as you do when play and stop unity). All of the other test programs start and stop the camera once, so we never saw the issue until now, I should have tried to start and stop the Unity test map multiple times when I first integrated the new camera driver in, but oh well (shame on me for lazy smoke testing). The actual fix for the camera issue is [here](https://github.com/brendanwalker/PS3EYEDriver/commit/b4f45cf9b16ac61c78ed28c74fee985c9a5985a8) in case you're curious. I checked in updated psmoveapi dlls and tools. If you get latest on the master branch in psmove-unity5 it should now be fixed. Let me know if this works for you and I'll close this issue. Thanks for the testing!

**Comment by toto5100** [comment]
It works now, awesome work !
No link with this issue, but do you think it would be possible to set an offset for position tracking, or manually set the position of the pscam relative to dk2 cam ? Because i cannot co register with enough precision, there is always an offset of ~15-20 centimeters with the real world position of the controller.

**Comment by brendanwalker** [comment]
Cool glad to hear that fixed it for you. And yes I can definitely add an offset parameter on the PSMoveManager component. I'll try to get to that this weekend. I opened a new [issue](https://github.com/brendanwalker/psmove-unity5/issues/11) for that so that I can close this one.
