### ISSUE TITLE
Unity requires reboot before tracking works again

### ISSUE THREAD

**Issue by FileCorrupted** [brendanwalker/psmove-unity5#12]
Not sure if this is a known issue, but for me Unity requires a reboot after running the scene once before it establishes tracking again.

**Comment by brendanwalker** [comment]
There was an existing [issue](https://github.com/brendanwalker/psmove-unity5/issues/10) about this very problem that I just resolved with this [fix](https://github.com/brendanwalker/psmove-unity5/commit/14de8d23b9d7be30d83338cc1c713a8ded68f20f). Basically there was a small bug in the new PS3EYEDriver code that caused the camera to not reset some state when the camera was closed. See PS3EyeDriver [PR](https://github.com/inspirit/PS3EYEDriver/pull/22) for details if you're curious about that. Some questions for you:

* Have you synced the latest version of PSMove-Unity5? 
    * This fix went in Feb 4 
* Which version of windows are you running? 
    * Win7 has sometimes been flaky for me with regard to handling of libusb camera support. I test mostly on WIn10 at home.
* With unity closed, can you start and stop the `ps3eye_sdl.exe` multiple times without issue?

**Comment by FileCorrupted** [comment]
Have you synced the latest version of PSMove-Unity5?
This fix went in Feb 4

I should be, downloaded yesterday.

Which version of windows are you running? 

Windows 10


With unity closed, can you start and stop the ps3eye_sdl.exe multiple times without issue?

I can start and stop it multiple times with no issue, running more than one instance causes some weirdness though.

Also, rotation seems to be mirrored in Unity (point it forwards and it rotates backwards). That might have something to do with me not using a rift atm.

**Comment by brendanwalker** [comment]
Ok bummer. This does sound like a new issue. I wonder if the worker thread is getting stalled out trying to shutdown the camera between runs. What does your console say between runs. Mine looks like this every start and stop game cycle:

Started Game:
> Setting up PSMove Tracking Context
PSMove tracker initialized.
Camera Dimensions: 640 x 480
PSMove fusion initialized.
PSMove Controllers count changed: 0 -> 1.

Stopped Game:
> Tearing down PSMove Tracking Context
Disconnecting PSMove controller 0
PSMove fusion disposed
PSMove tracker disposed

I could add an option that would allow the camera running between game sessions since it's just a background thread. That wouldn't be a fix exactly but it would work around the issue.

As for the orientation thing, what HMD type are you using? I've never tried testing this plugin with anything by my DK2 at home. I could certainly add an HMD type option that changes how the orientation quaternion returned from psmoveapi is treated.

**Comment by FileCorrupted** [comment]
Started Game:
- loaded lib Assets/Plugins/x86_64/psmoveapi.dll
- loaded lib Assets/Plugins/x86_64/psmoveapi_tracker.dll
- Setting up PSMove Tracking Context
- PSMove tracker initialized.
- Camera Dimensions: 640 x 480
- PSMove fusion initialized.
- PSMove Controllers count changed: 0 -> 2.

Stopped Game:
- Tearing down PSMove Tracking Context
- Disconnecting PSMove controller 0
- Disconnecting PSMove controller 1
- PSMove fusion disposed
- PSMove tracker disposed

Second time running:
- loaded lib Assets/Plugins/x86_64/psmoveapi.dll
- loaded lib Assets/Plugins/x86_64/psmoveapi_tracker.dll
- Setting up PSMove Tracking Context


So it seems it doesn't get past setting up the Tracking Context the second time around. I think running it between sessions is a fine temporary (Or honestly, even permanent) solution. 

As for the mirrored rotation, that was a fault on my end. I miscalibrated somewhere along the ways and then tried to fix it in game by mirroring to quaternion, after fixing the calibration I forgot to remove the mirror of the quaternion.

**Comment by brendanwalker** [comment]
Ah ok. Sorry I misunderstood what you meant by "not using a rift". I gave this use case a try (by disabling my rift) but wasn't able to repro you issue in that fasion either. Good to know about the orientation stuff though. One less thing to worry about.

As for the persistent tracking context stuff, I made a large refactor to allow tracker remain active between game runs. Sadly I found out that even if you have a singleton class with your state that persists after you stop the game, Unity will reset that state the next time you start the game (including any threads you had active). Apparently this is problem other people have hit trying something similar (editing state in game and having it persist into the editor and into the next game run). It's possible to serialize state across the restart boundary in some [cases](http://ivanozanchetta.com/gamedev/unity3d/unity-serialization-behind-scriptableobject/), but in this situation I have DLLs that get unloaded too which borks the tracking state. So basically that option is out. However I was able to pull back from this larger change and clean up the worker thread code and hopefully make it a bit more reliable. I have that change checked into a new thread_refactor branch here:

https://github.com/brendanwalker/psmove-unity5/tree/thread_refactor

Would you mind pulling down the build from that branch and seeing if that fixes your problem?

I should also mention that I'm working with cboulay (author of psmove-ue4) to make the psmove stuff hosted in a windows service. The game client will connect to this service over a socket. This allows the service to maintain camera and tracking state independent of game client starting or stopping. It would fix the problem you are seeing here. However, while progress is going well with that, we are at least a month out from anything publicly testable.

**Comment by FileCorrupted** [comment]
Thanks! That appears to have fixed it!

**Comment by brendanwalker** [comment]
Sweet! Glad to hear that worked for you. I'll merge this back up to master and close this issue.
