### ISSUE TITLE
psmovepair.exe built in debug mode.

### ISSUE THREAD

**Issue by MHDante** [brendanwalker/psmove-unity5#2]
Hello, I'm just letting you know that your most recent update to the Tools broke psmovepair. On launch, it requests MSVCR120D.dll which means that the app was built using debug flags. The previous version worked for me, but you might want to rebuild the tool.

**Comment by brendanwalker** [comment]
Whoops! Thanks for the notification. I'm working on fixing this now.

**Comment by brendanwalker** [comment]
I just checked in release mode executables in this check-in:
https://github.com/brendanwalker/psmove-unity5/commit/531f2ca603764baee1cc20908504cca2ddb08289
I believe this should fix the issue, but let me know if it doesn't.
