### ISSUE TITLE
psmovepair.exe and psmove-pair-win.exe output doesn't match Wiki Documentation

### ISSUE THREAD

**Issue by pomeroyb** [brendanwalker/psmove-unity5#7]
First off, huge thanks for setting this project up and for writing such great documentation!

I'm currently trying to pair my controller, but what I'm seeing in the console output doesn't match what the wiki says.

# psmovepair.exe

## Wiki documentation: 
> Plug the controller into the computer via the mini-USB cable. Run Assets\Plugins\x86_64\psmovepair.exe. This will write the computer's Bluetooth address to the controller but will ultimately fail in establishing the connection. Follow the on-screen instructions but you will be pressing Ctrl+C before the LED is solidly lit.

## My console output:
```
C:\Users\Brandon\Downloads\psmove-unity5-master\psmove-unity5-master\Assets\Plug
ins\x86_64>psmovepair.exe
Connected controllers: 1
[PSMOVE WARNING] Magnetometer in 00:07:04:2a:da:0e not yet calibrated.
Ignoring non-USB PSMove #1
```

My output doesn't seem to attempt to establish a connection, and there are no on-screen instructions -- the program ends on its own.

# psmove-pair-win.exe

## Wiki sample code (Truncated for brevity):
```
==== Looking for Bluetooth radios ====

  (0)  5c:f3:70:64:54:10  SACHSLAB-WIN8

Using the only available Bluetooth radio.
Making radio discoverable.


==== Connecting new controllers ====

Device: (0)  00:06:f7:97:32:e8  Motion Controller
                          CoD: 0x00002508, CON: 0, REM: 1, AUTH: 0

device #0: Move Motion Controller detected
Device removed - retry
Device: (0)  00:06:f7:18:cd:f3  Motion Controller
                          CoD: 0x00002508, CON: 0, REM: 0, AUTH: 0

device #0: Move Motion Controller detected
```

## My console output:
```
C:\Users\Brandon\Downloads\psmove-unity5-master\psmove-unity5-master\Assets\Plug
ins\x86_64>psmove-pair-win.exe
==== Looking for Bluetooth radios ====

  (0)  5c:f3:70:6a:c3:b6  BRANDONTOWER

Using the only available Bluetooth radio.


==== Connecting new controllers ====

No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
No Bluetooth devices found.
```

My output doesn't seem to "Make radio discoverable", and obviously is having trouble finding devices, even with me mashing the PS button on the Move. I have to Ctrl-C to stop the program.

I am running Windows 7 64 bit, and have been opening these .exe files in administrator mode. I restarted my PC after installing drivers, and my bluetooth settings have discovery enabled:

![](http://i.imgur.com/Fh4l75p.png)

Any ideas? I'm planning to uninstall/reinstall the bluetooth drivers, but I won't be able to do that until later tonight. 

Thanks,
Brandon Pomeroy

**Comment by brendanwalker** [comment]
You mentioned you were running in Win7. Did you grab from the master branch or the [Win7 branch](https://github.com/brendanwalker/psmove-unity5/tree/win7)? I ask because there is an issue in win7 with HIDApi that causes the psmovepair code to not work right. The fix I have for it now is in the win7 branch because I haven't had time to make it play nice in win8+ and merge it back into master. I really should update the docs to call out the other branch for win7 users...

**Comment by pomeroyb** [comment]
Nope, used the master branch -- didn't even think to check other branches. That might explain it, haha. I'm at the office right now so I can't give it a try until tonight, but I'll let you know how it goes.

**Comment by pomeroyb** [comment]
That totally solved my problem, thanks for the suggestion! I'm connected and tracking my controller. :)
